# Generated by Django 5.0 on 2024-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
